spotifyd:
    username: ENC[AES256_GCM,data:ovDRv5flT24Gt7m10H8yh8w4URFlEQ==,iv:DURK3rq9p7dAodaU55B1Qq2ywViCgYQDGdawRYQYORg=,tag:Xh0mZqxckx2P5FwEYOFg0g==,type:str]
    password: ENC[AES256_GCM,data:6C82Gg324Eqr33E2wsm8+srvhqAQeFcnHklzwpF4ucjlaRmclsS5X1n9dfoSl3rtq+zpXDMB4OPkyFFclkG4WQN0L1Cb1Fykab41ejAegSaa,iv:9x/NduGeNXW0VG1TaxYelaHUq+PARYavs8CxWKtUd3o=,tag:MGN859xOhDkdVsBUd2GKDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dl2ldz7s96plfwl0vaur78cy6dwq0tv2726zq5frfykvxkdh2qcqmn6flk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiU3VXclJ3amg0alFxaUk0
            cFczUEFVMW9VNUdYWXRhelZvdzNYckRNbFRBCmExajBMa2hObWw0WmpiQVg1MTlU
            THZMa3JidlZNcGI3SGE5VlIxR3pDZmcKLS0tIC9OSlZpQWJHUW9wcU8ybkozYU1i
            bGtxaEhiNGFMclhtNW4yak1JRUxacWMK0td610Rkhye8+NW/IjSUqVI9h93grapY
            VSpwMf7P4WBewkL7CVNg3n6/49ipb1L2TK6VHxoLNgBcdt7mdQlOgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zswlplhkdu0pzx08uruxwq7lgumvtahrnllcs34xpuxru9xqy3aqtjrkhv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxa1FuQS9xcWF4dW5QQldJ
            UFV4THp0S051UGxFa3RzQk1vSk5lQjljdGdZCjY3V1RPMG1GKzJQUzNrWDBHZjNo
            SzNObTZLVW5ScTBxazJvZDNBYXhNdHMKLS0tICsvdWlVaFpzcEFqcTJ3bTF6d2Ix
            SGRZdndYVVNKTnVMZUFIRkJyenFyOXMKpCHomOSP0EvXkGJgneySYEJoNJ8Da6Em
            Se3vSkSyhvyENmkDLfwMBiPhfiZ+UVKlIGZlYxCEH9XywzuAvpneOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T15:00:38Z"
    mac: ENC[AES256_GCM,data:gQXkW+Jb3Fz2CZUyfs2SEMiI9t5jqKytUsdDJhcKZ/TMDAkBWh2w92srBcmD4Z5F/K/tD0vo5YKMSvlvxIMPYAMGod+sfg3iDF/5yot44UC+HaM4MUXw8wqfIyakzzOUDVoZuDkHAIRYB/4Ot81wltj1Ma4Bt6zDZkbkcqVPxWk=,iv:/QdKqBS/7VY/StOBLzh1HW4VupJcVx2DGFsAeJj76uc=,tag:kWdoWuORqdt+zi5s2RDDlw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
